import Header from '@/components/Header'
import './globals.css'
import { Inter } from 'next/font/google'
import MobileHeader from '@/components/Header/mobileHeader'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt">
      <body className={inter.className}>
        <Header />
        <MobileHeader />
        {children}
      </body>
    </html>
  )
}
